#nullable enable
namespace TCULauncher;

public class LauncherGlobals
{
  public static readonly bool KILL_GAME_ON_LAUNCHER_EXIT = false;
  public static readonly bool SHOW_STRING_ID_WHEN_UNLOCALIZED = false;
  public static readonly bool STORE_PATCH_DOWNLOADS = true;
  public static readonly bool STORE_ENCRYPTED_PATCH_DOWNLOADS = true;
  public static readonly bool RETRIEVE_LOCAL_PATCH_DOWNLOADS = true;
  public static readonly int KEEP_DOWNLOAD_CACHE_FOR_DAYS = 30;
  public static readonly bool ALLOW_DATA_JSON = false;
  public static readonly bool VERIFY_LOCAL_PATCH_DOWNLOADS = true;
  public static readonly string FILE_NAME_EXE = "TheCrew.exe";
  public static readonly string STEAM_API_FILENAME = "steam_api.dll";
  public static readonly string STEAM_API_FILENAME_64 = "steam_api64.dll";
  public static readonly int STEAM_APPID = 241560;
  public static readonly string STEAM_START_LINK = "steam://rungameid/";
  public static readonly string FILE_USERDATA = "userdata.xml";
  public static readonly string DIR_DOWNLOADS = "\\downloads\\";
  public static readonly string DIR_PATCHES = LauncherGlobals.DIR_DOWNLOADS + "\\patches\\";
  public static readonly string DIR_LANG = "\\lang\\";
  public static readonly string DIR_LOCAL_TEMP = "\\_temp\\";
  public static readonly string FILE_UPDATER_EXE = "TCULauncherUpdater.exe";
  public static readonly int SAVEGAME_NAME_CHARS_MIN = 3;
  public static readonly int SAVEGAME_NAME_CHARS_MAX = 24;
  public static readonly string SAVEGAME_NAME_CHARS_WHITELIST = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890-_. ";
  public static readonly string SAVEGAME_DEFAULT_NAME = "TCUPlayer";
  public static readonly string SAVEGAME_EXT = "tcusave";
  public static readonly string DUMPED_SAVEGAME_EXT = "json";
  public static readonly string DUMPED_SAVEGAME_DEFAULT_NAME = "data.json";
  public static readonly string SAVE_BAK_EXT = ".bak";
  public static readonly string LANG_FILE_EXT = "xml";
  public static readonly string CHEAT_MANIFEST = "tcu.manifest.cheats.xml";
  public static readonly string TCUPATCH_MANIFEST = "tcu.manifest.patch.xml";
  public static readonly string SERVER_CONFIG_FILE = "server.ini";
  public static readonly string LOCAL_IP = "127.0.0.1";
  public static readonly string MANUAL_PATCH_VERSION_PLACEHOLDER = "unknown";
  public static readonly string MANUAL_PATCH_EXTENSIONS = "*.zip;*.rar;*.7z";
  public static readonly int TCUNET_NEWS_REQUEST_FREQ = 6;
  public static readonly string[]? USERDATA_TOP_COMMENTS = new string[5]
  {
    " This is your TCU Launcher userdata file. It contains your Launcher settings, Game Instances and Server Instances.  Do not edit this file while the Launcher is running. ",
    " ",
    " There aren't really any hidden options here that aren't available in the Launcher itself, with the exception of these instance attributes: ",
    " - \"forcepatched=1\": forces the Launcher to always treat the desired game instance as if it's patched. ",
    $" - \"runEXE=...\": runs the specified file (relative to the game install dir) instead of the default \"{LauncherGlobals.FILE_NAME_EXE}\", in case it's required."
  };
  public static readonly string SERVER_INI_TOP_COMMENT = $"# This file was auto-generated by the TCU Launcher.{Environment.NewLine}# We recommend you don't modify it.";
}
